table DimCategory
	lineageTag: f9a6ba0d-9d2e-411f-a2ce-f7b74cb9bbf1

	column CategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 6ad84da3-5080-4d97-b289-2598cb9b6244
		summarizeBy: none
		sourceColumn: CategoryKey

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: 11e7b783-f056-4a58-bd8c-8eef12808d74
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 134bb659-b282-4b6a-aa35-7f5dba437405
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column DivisionName
		dataType: string
		lineageTag: cea9fdbe-6420-4b6e-86d1-e5d00f8d52ed
		summarizeBy: none
		sourceColumn: DivisionName

		annotation SummarizationSetBy = Automatic

	partition DimCategory = m
		mode: import
		source =
				let
				Source = Csv.Document(File.Contents(ProjectDataFolder & "\DimCategory.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CategoryKey", Int64.Type},{"CategoryName", type text},{"Department", type text},{"DivisionName", type text}})
				in
				#"Changed Type"

	annotation PBI_ResultType = Table

